# .github/release.yml

changelog:
  exclude:
    authors:
      - octocat
  categories:
    - title: Breaking Changes 💥
      labels:
        - ":boom: breaking"
    - title: Exciting New Features 🎉
      labels:
        - ":tulip: enhancement"
    - title: Other Changes
      labels:
        - "*"
