services:
  backend-deno:
    image: denoland/deno:1.39.0
    command: [ "test", "--allow-all", "/app/cucumber/test.ts", "--",
               "--features", "/features",
               "--steps", "/app/cucumber/steps", ]
    volumes:
      - .:/app
      - ../backend-features:/features
