services:
  backend-deno:
    image: denoland/deno:2.1.2
    working_dir: /app
    command: [ "test", "--allow-all", "./cucumber/test.ts", "--",
               "--features", "/features",
               "--steps", "/app/cucumber/steps", ]
    volumes:
      - .:/app
      - ../backend-features:/features
