services:

  ##
  ## go commands
  ##

  style:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "gofmt", "-w", "." ]
    volumes:
      - .:/app
    profiles: [ 'style' ]

  test:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ 'go', 'test' ]
    volumes:
      - .:/app
      - ../backend-features:/backend-features
    profiles: [ 'test' ]

  ##
  ## end-to-end example
  ##

  sub:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ 'go', 'run', 'samples/sub/main.go', '--dev', '--NATS_URL=nats://nats:4222' ]
    volumes:
      - .:/app
    networks: [ 'nats-network' ]
    profiles: [ 'dev' ]
    depends_on: [ 'nats' ]
    restart: unless-stopped

  pub:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ 'go', 'run', 'samples/pub/main.go', '--dev', '--NATS_URL=nats://nats:4222' ]
    volumes:
      - .:/app
    networks: [ 'nats-network' ]
    profiles: [ 'dev' ]
    depends_on: [ 'nats' ]

  nats:
    image: nats:latest
    command: [ '-c', '/etc/nats/nats.conf' ]
    volumes:
      - ./.nats.conf:/etc/nats/nats.conf
    ports:
      - '0.0.0.0:4222:4222'
      - '127.0.0.1:8222:8222'
      - '127.0.0.1:6222:6222'
      - '0.0.0.0:9222:9222'
    networks: [ 'nats-network' ]
    profiles: [ 'dev' ]
    restart: unless-stopped

networks:
  nats-network:
    name: nats-network
