# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Telestion Documentation

repo_url: https://github.com/wuespace/telestion
repo_name: wuespace/telestion
edit_uri: edit/main/docs/docs/
copyright: |
  <p>
  &copy; 2023 WüSpace e. V.
  <p>
  <a href="https://www.wuespace.de/legal-notice/" target="_blank">Legal Notice</a> 
  | <a href="https://www.wuespace.de/privacy-policy/" target="_blank">Privacy Policy</a>
  </p>

theme:
  name: material
  font: false
  custom_dir: overrides
  palette:
    - schema: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: _theme_img/logo.svg
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - navigation.footer
    - navigation.indexes
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.action.view
    - search.highlight

extra_css:
  - _css/custom.css

extra_javascript:
  - _js/main.js
  - _js/mermaid-js/mermaid.min.js

markdown_extensions:
  - smarty
  - toc:
      permalink: true
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.smartsymbols
  - pymdownx.escapeall # support for backslash escapes in typedoc output
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - awesome-pages
  - tags
  - search
  - social
  - privacy
  - git-revision-date-localized:
      enable_creation_date: true

extra:
  social:
    - link: /_writers-guide
      icon: material/typewriter
      name: Writers Guide
