# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Telestion Documentation

theme:
  name: material
  font: false
  custom_dir: overrides
  palette:
    - schema: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: _theme_img/logo.svg
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - navigation.footer
    - navigation.indexes
    - content.code.copy
    - content.code.annotate

extra_css:
  - _css/custom.css

extra_javascript:
  - _js/main.js

markdown_extensions:
  - smarty
  - toc:
      permalink: true
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - awesome-pages
  - tags
  - search
  - privacy

extra:
  social:
    - link: /_writers-guide
      icon: material/typewriter
      name: Writers Guide
