name: Backend Go CI

on: [push, pull_request]

defaults:
  run:
    working-directory: ./backend-go

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 📥
        uses: actions/checkout@v3.6.0
      - name: Setup Virtual Environment 🛠️
        run: |-
          ../backend-features/tools/setup-venv.sh
      - name: Run Tests 🧪
        run: |-
          . ../backend-features/.venv/bin/activate
          ../backend-features/run-tests.py -v .
