name: Deploy docs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
      - name: Setup Node/pnpm
        uses: actions/setup-node@v2
        with:
          node-version: 21
      - name: Build API Reference for frontend-react
        working-directory: frontend-react
        run: |
          pnpm install --frozen-lockfile
          pnpm run docs
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.26
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: docs.telestion.wuespace.de
          CONFIG_FILE: docs/mkdocs.yml
          EXTRA_PACKAGES: build-base
          REQUIREMENTS: docs/requirements.txt